# Generated by Django 2.1.4 on 2018-12-08 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address_id', models.IntegerField(primary_key=True, serialize=False)),
                ('street', models.CharField(max_length=20)),
                ('building_number', models.IntegerField()),
                ('city', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'address',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('appointment_date', models.DateField()),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='webapp.Address')),
            ],
            options={
                'db_table': 'appointment',
            },
        ),
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('clinic_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('reception_telephone', models.IntegerField()),
                ('email', models.CharField(max_length=50)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='webapp.Address')),
            ],
            options={
                'db_table': 'clinic',
            },
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('data_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=50)),
                ('telephone_number', models.IntegerField()),
                ('email', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'data',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doctor_id', models.IntegerField(primary_key=True, serialize=False)),
                ('specialization', models.CharField(max_length=50)),
                ('company_telephone', models.IntegerField()),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='webapp.Clinic')),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='webapp.Data')),
            ],
            options={
                'db_table': 'doctor',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.IntegerField(primary_key=True, serialize=False)),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='webapp.Data')),
            ],
            options={
                'db_table': 'patient',
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='webapp.Doctor'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='webapp.Patient'),
        ),
    ]
